// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTask(arg1:string):Promise<string>;

export function GetEncodedTask(arg1:string):Promise<string>;

export function ReturnTasks():Promise<string>;

export function UpdateTask(arg1:string):Promise<string>;
