// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetEncodedTask(arg1) {
  return window['go']['main']['App']['GetEncodedTask'](arg1);
}

export function ReturnTasks() {
  return window['go']['main']['App']['ReturnTasks']();
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
